# Generated by Django 5.0.6 on 2024-06-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Participant',
        ),
    ]
