# Generated by Django 5.0.6 on 2024-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_user_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
