# Generated by Django 5.0.6 on 2024-06-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_participant_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
